version: '3'

services:
  api:
    container_name: api 
    build:
       context: .
       dockerfile: Api.Dockerfile
    ports:
      - "8888:80"
  web:
    container_name: web
    build:
        context: .
        dockerfile: UI.Dockerfile
    ports:
      - "7777:80"
    environment:
      - API_URL=http://api:80

